#+TITLE:[research][notes]The Developer's Guide to Azure
#+AUTHOR:Vinícius Gajo Marques Oliveira
#+DATE:2021-12-02

* Virtual Machines
  Hosting your applicaiton in a VM in Azure Virtual Machines provides you with a
  lot of control over how you host your application. However, you're responsible
  for  maintaining  the  environment,  including patching  the  OS  and  keeping
  antivirus programs up to date.
  
** Azure Batch
   If  you need  to run  large-scale batch  or high-performance  computing (HPC)
   applications on VMs, you can use Azure Batch.

* Azure App Service
  Is one of the key services in Azure that you can use to host your applications
  created with popular frameworks (.NET, .NET core, Node.js, Java, PHP, Ruby, or
  Python) in containers, or  running on any OS. Azure App  Service also adds the
  power  of Azure  to  your applications,  including  security, load  balancing,
  autoscaling, and automated management.

* Using events and messages in your application
  The  core of  messaging in  Azure is  Service Bus.  Service Bus  encompasses a
  collection of services that you use for messaging patterns. The most important
  services are Azure Service Bus queues and topics.

* Event Hubs
  Can help enterprises  capture massive amounts of data to  analyze or transform
  and move for later use.

  Event Hubs  is designed  for massive data  ingestion. It  effortlessly handles
  millions of  messages per  second. It  retains messages  for up  to 7  days or
  indefinitely by writing messages to a  data store using the Event Hubs Capture
  feature.
