#+TITLE: [note] Microsoft Certified: Azure Fundamentals
#+AUTHOR: Vinícius Gajo Marques Oliveira

* Azure Fundamentals part 1: Describe core Azure concepts
  Azure is  a cloud  computing platform.  Azure services  range from  simple web
  services for  hosting your  business presence  in the  cloud to  running fully
  virtualized computers for you to run your custom software solutions.

  Azure provides a wealth of cloud-based services like:
  + Remove storage
  + Database hosting
  + Centralized account management
  + AI
  + IoT

  ---
  What is  cloud computing?

  It's the delivery of computing services  over the internet, which is otherwise
  known  as the  cloud.   These services  include  servers, storage,  databases,
  networking, software, analytics, and intelligence.

  To put  it another way,  cloud computing  is a way  to rent compute  power and
  storage from someone else's datacenter.

  ---
  What is Azure?

  Azure  is  a continually  expanding  set  of  cloud  services that  help  your
  organization meet your current and future business challenges. Azure gives you
  the freedom  to build,  manage, and  deploy applications  on a  massive global
  network using your favorite tools and frameworks.

  ---
  What is the Azure portal?

  Is a web-based,  unified console that provides an  alternative to command-line
  tools. With the Azure portal, you  can manage your Azure subscription by using
  a graphical user interface.

  ---
  What is Azure Marketplace?

  Azure  Marketplace helps  connect users  with Microsoft  partners, independent
  software vendors, and startups that are offering their solutions and services,
  which are optimized to run on Azure.

  ---
  Most common used categories in Azure:

  + Compute:
    Hosting applications and services.
  + Networking:
    Linking compute resources and providing access to applications.
  + Storage
  + Mobile
  + Databases
  + Web
  + Internet of Things (IoT)
  + Big data
  + AI
  + DevOps

** Get started with Azure accounts
   To create and use Azure services, you need an Azure subscription. When you're
   completing  Learn modules,  most  of  the time  a  temporary subscription  is
   created for you, which runs in  an environment called the Learn sandbox. When
   you're working  with your own  applications and  business needs, you  need to
   create an  Azure account, and a  subscription will be created  for you. After
   you've  created   an  Azure  account,   you're  free  to   create  additional
   subscriptions. For example, your company might use a single Azure account for
   your  business and  separate  subscriptions for  development, marketing,  and
   sales departments. After you've created  an Azure subscription, you can start
   creating Azure resources within each subscription.

   Azure account > Subscriptions > Resource groups > Resources.

   The Azure free account includes:

   + Free access to popular Azure products for 12 months.
   + A credit to spend for the first 30 days.
   + Access to more than 25 products that are always free.

** What are some cloud computng advantages?
   + High availability
     Depending  on  the service-level  agreement  (SLA)  that you  choose,  your
     cloud-based apps can provide a  continuous user experience with no apparent
     downtime, even when things go wrong.

   + Scalability:
     + Vertically:
       Increase compute capacity by adding RAM or CPUs to a virtual machine.
     + Horizontally:
       Increase  compute capacity  by  adding instances  of  resources, such  as
       adding VMs to the configuration.

   + Elasticity:
     You can  configure cloud-based apps  to take advantage of  autoscalling, so
     your apps always have the resources they need.

   + Agility:
     Deploy and configure cloud-based resources quickly as your app requirements
     change.

   + Geo-distribution:
     You can  deploy apps  and data  to regional  datacenters around  the globe,
     thereby ensuring  that your customers  always have the best  performance in
     their region.

   + Disaster recovery:
     By taking advantage  of cloud-based backup services,  data replication, and
     geo-distribution, you can  deploy your apps with the  confidence that comes
     from knowing that your data is safe in the event of disaster.

** Capital expenses vs. operating expenses
   There are two different types of expenses that you should consider:

   + Capital Expenditure (CapEx):
     Is  the up-front  spending of  money on  physical infrastructure,  and then
     deducting that up-front expense over time. The up-front cost from CapEx has
     a value that reduces over time.

   + Operational Expenditure (OpEx):
     Is spending  money on services or  products now, and being  billed for them
     now. You can deduct this expense in the same year you spend it. There is no
     up-front cost, as you pay for a service or product as you use it.

** Organizing structure for resources in Azure
   The organizing structure for resources in Azure has four levels:

   + Management groups:
     These groups  help you manage  access, policy, and compliance  for multiple
     subscriptions.  All  subscriptions  in  a  management  group  automatically
     inherit the conditions applied to the management group.

   + Subscriptions:
     A subscription  groups together  user accounts and  the resource  that have
     been  created by  those user  accounts.  For each  subscription, there  are
     limits  or quotas  on  the amount  of  resources that  you  can create  and
     use. Organizations can use subscriptions  to manage costs and the resources
     that are created by users, teams, or projects.

     An account can  have one subscriptions or multiple  subscriptions that have
     different billing models and to which you apply different access-management
     policies.

   + Resource groups:
     Resources  are  combined into  resource  groups,  which  act as  a  logical
     container into which Azure resources  like web apps, databases, and storage
     accounts are deployed and managed.

     If you delete a resource group,  all resources contained within it are also
     deleted. Resource groups make it easy to remove a set of resources at once.

     Resource groups  are also  a scope for  applying role-based  access control
     (RBAC) permissions. By  applying RBAC permissions to a  resource group, you
     can ease administration and limit access to allow only what's needed.

   + Resources:
     Are instances of services that  you create, like virtual machines, storage,
     or SQL databases.
