#+Title:[Curso]Introdução à ciência de dados 3.0
#+Author:Vinícius Gajo Marques Oliveira

* O que é ciência de dados?
  A quantidade de dados gerados  pela humanidade estão em constante crescimento,
  possibilitando novos tipos  de análises.  Com base nesta  afirmação é possível
  perceber  que todos  os negócios  podem se  beneficiar de  insights obtidos  a
  partir de dados (data-driven solutions).

  + Data science: técnica para extrair insights a partir de dados.
    + Análise de negócios ou inteligência competitiva.
    + Tomar decisões com base em dados.
  + Estatística, matemática, programação, computação, negócios, etc.
    + O que aconteceu? (definir o problema)
    + Porque aconteceu? (análise de dados do problema)
    + Acontecerá novamente? (machine learning)
    + O que deve ser feito? (propor uma solução para o tomador de decisão)
  + Funções (não profissões - não requer graduação, regularização):
    + Cientista de dados
    + Engenheiro de dados
    + Analista de dados
    + Engenheiro de machine learning
    + Engenheiro de IA
    + Engenheiro DataOps
    + Arquiteto de dados
    + Engenheiro blockchain
    + Desenvolvedor RPA (robotic process automation)
  + Áreas da estatística
    + Probabilidade
      + Aleatoriedade e incerteza.
    + Estatística descritiva
      + Coleta, organização, apresentação, análise e síntese de dados obtidos de uma população ou amostra.
      + Analista de dados.
    + Estatística inferencial
      + Estimar informações sobre uma população a partir dos resultados observados em uma amostra.

* Machine Learning e MLOps
  Todo projeto de machine learning é um projeto de ciência de dados. Entretanto,
  nem todo projeto de ciência de dados precisa envolver machine learning!

  Machine learning é um  subcampo da IA que dá aos  computadores a habilidade de
  aprender  sem serem  explicitamente programados  para isso.   Aprendizado é  a
  capacidade  de se  adaptar,  modificar  e melhorar  seu  comportamento e  suas
  respostas.

  Machine  learning  é   um  método  de  análise  de  dados   que  automatiza  o
  desenvolvimento de modelo analíticos.  Usando algoritmos que aprendem a partir
  de  dados, o  aprendizado de  máquina  permite que  os computadores  encontrem
  padrões ocultos  sem que sejam  explicitamente programados para  procurar algo
  específico.

  Deep learning  usa redes neurais profundas  (técnica que mais se  assemelha ao
  aprendizado humano). Usado para os desafios mais complexos.

  + Aprendizado supervisionado: dados rotulados. Aprende com exemplos (dados históricos).
    + Classificação: resultado é uma classe.
    + Regressão: resultado numérico.
  + Aprendizado não-supervisionado: dados não rotulados.
