#+TITLE: [book] Security Engineering
#+EDITION: 3rd

* About the author
  + Name: Ross Anderson

  Graduated in math and  natural science from Cambridge in the  1970s, and got a
  qualification  in  computer  engineering.  First  working  experience  in  the
  avionics field.  Later studied cryptology  and computer security,  working for
  banks during the 1980s.

  Moved to  academia in 1992  but continued to  consult to industry  on security
  technology. Taught  security and cryptology to  students for a few  years, and
  realized  that the  existing textbooks  were too  narrow and  theoretical: the
  security  textbooks focused  on  the access  control  mechanisms in  operating
  systems, while the cryptology books  developed the theory behind bryptographic
  algorithms and protocols.

* Part I
  + Cover the basics.
  + No fancy background required.

  These  chaperts  cover basic  material,  and  largely  follow what  is  taught
  first-year and second-year  undergraduates at Cambridge. But I  hope that even
  experts will find the case studies of interest and value.

** Chapter 1: What is security engineering?
   Security engineering  is about building  systems to remain dependable  in the
   face  of malice,  error, or  mischance. As  a discipline,  it focuses  on the
   tools, processes, and methods needed  to design, implement, and test complete
   systems, and to adapt existing systems as their environment evolves.

   Security  engineering  requires  cross-disciplinary expertise,  ranging  from
   cryptography and  computer security  through hardware tamper-resistance  to a
   knowledge of economics, applied psychology, organisations and the law. System
   engineering  skills,   from  business   process  analysis   through  software
   engineering to evaluation  and testing, are also important; but  they are not
   sufficient,  as  they  deal  only   with  error  and  mischance  rather  than
   malice. The security engineer also  needs some skill at adversarial thinking,
   just like  a chess  player; you  need to  have studied  lots of  attacks that
   worked in  the past,  from their  openings through  their development  to the
   outcomes.

   Security and safety are becoming ever  more intertwined as we get software in
   everything.

   [...] The  military environment was until  recently one of the  few customers
   for software systems that had to be maintained for decades. Now that software
   and internet connectivity are finding their way into safety-critical consumer
   goods  such  as  cars,  software  sustainability is  becoming  a  much  wider
   concern. In 2019, the European Union passed  a law demanding that if you sell
   goods with  digital components,  you must maintain  those components  for two
   years, or  for longer if  that's a reasonable  expectation of the  customer -
   which  will mean  ten years  for  cars and  white goods.   If you're  writing
   software for  a car of fridge  that will be  on sale for seven  years, you'll
   have to maintain it for almost twenty years. What tools should you use?

   [...] Ignoring the human components, and thus neglecting usability issues, is
   one of the largest causes of security failure.

*** A framework
    To build really dependable systems, you need four things to come together.

    There's policy: what you're supposed to achieve.

    There's mechanism: the ciphers,  access controls, hardware tamper-resistance
    and other machinery that you use to implement the policy.

    There's assurance: the  amount of reliance you can place  on each particular
    mechanism, and how well they work together.

    There's  incentive: the  motive  that people  guarding  and maintaining  the
    system have to do their job properly, and also the motive that the attackers
    have to try to defeat your policy.

*** Definitions
    + System:
      (1) A product or component, such as a cryptographic protocol, a smartcard,
      or the  hardware of a phone,  a laptop or server;

      (2) One or more of the  above plus an operating system, communications and
      other infrastructure;

      (3) The  above plus  one or  more applications  (banking app,  health app,
      media player,  browser, accounts/payroll  package, and  so on  - including
      both client and cloud components);

      (4) any or all of the above plus IT staff;

      (5) any or all of the above plus internal users and management;

      (6) any or all of the above plus customers and other external users;

    + Subject:
      A physical person in any role  including that of an operator, principal or
      victim.

    + Person:
      Either  a  physical  person  or  a  legal person  such  as  a  company  or
      government.

    + Principal:
      Is an entity that participates in a  security system. This entity can be a
      subject, a  person, a  role, or  a piece  of equipment  such as  a laptop,
      phone, smartcard, or card reader. A principal can also be a communications
      channel (which might be  a port number, or a crypto  key, depending on the
      circumstance). A  principal can  also be a  compound of  other principals;
      examples are a  group (Alice or Bob), a conjunction  (Alice and Bob acting
      together),  a  compound  role  (Alice  acting  as  Bob's  manager)  and  a
      delegation (Bob acting for Alice in her absence).

    + Group:
      A set of principals.

    + Role:
      Set of functions assumed by different persons in succession.

    + Identity:
      When we have to be careful, I will use it to mean a correspondence between
      the names of two principals signifying  that they refer to the same person
      or equipment.

    + Trusted:
      [NSA definition]  A trusted system of  component is one whose  failure can
      break the security policy.

    + Trustworthy:
      [NSA definition] A trustworthy system or component is one that won't fail.

    + Secrecy:
      Is an engineering term that refers to the effect of the mechanisms used to
      limit  the  number of  principals  who  can  access information,  such  as
      cryptography os computer access controls.

    + Confidentiality:
      Involves an  obligation to protect  some other person's  or organisation's
      secrets if you know them.

    + Privacy:
      Is  the ability  and/or right  to  protect your  personal information  and
      extends to the ability and/or right  to prevent invasions of your personal
      space  (the  exact  definition  of   which  varies  from  one  country  to
      another). Privacy can extend to families  but not to legal persons such as
      corporations.

    + Hack:
      Something  a  system's  rules  permit, but  which  was  unanticipated  and
      unwanted by its designers.

** Chapter 2 - Who is the opponent?
   Ideologues may deal with the world as they would wish it to be, but engineers
   deal  with the  world as  it is.  If you're  going to  defend systems  agains
   attack, you first need to know who your enemies are.

   Model your enemy:

   + What sort of capabilities will the adversaries have, and what motivation?

   + How certain are you of this assessment, and how might it change over the
     system's lifetime?

*** Spies
    Governments have a range of tools  for both passive surveillance of networks
    and active attacks on computer systems. Hundreds of firms sell equipment for
    wiretapping, for radio  intercept, and for using  various vulnerabilities to
    take over computers, phones and other digital devices.

**** Prism
     A  system to  collect the  Gmail and  other data  of users  who are  not US
     citizens or  permanent residents, and  is carried  out under an  order from
     FISA court.

     Prism was  an internal  NSA codename  for an access  channel that  had been
     privded  to the  FBI  to  conduct warranted  wiretaps.  US  law permits  US
     citizens to be  wiretapped provided an agency convinces a  court to issue a
     warrant,  based on  "probable  cause" that  hey  were up  to  no good;  but
     foreigners could be wiretapped freely.

**** Tempora
     A  program   to  collect   intelligence  from  international   fibre  optic
     cables. [...] the journalist Duncan  Campbell had described a system called
     Echelon in 1988 which tapped  the Intersat satellite network, keeping voice
     calls  on  tape while  making  metadata  available  for searching  so  that
     analysts could select traffic to or from phone numbers of interest. Snowden
     gave us an  update of the technology. In Cornwall  alone, 200 transatlantic
     fibres were tapped  and 46 could be  collected at any one time.  As each of
     these carried  10 Gb/s, the total  data volume could  be as high as  21Pb a
     day,  so  the  incoming  data   feeds  undergo  massive  volume  reduction,
     discarding  video, news  and the  like.  Material was  then selected  using
     selectors - not just phone numbers but more general search terms such as IP
     addresses - and stored for 30 days in case it turns out to be of interest.

**** Muscular
     One of the applications running on  top of Tempora was Muscular. [...] this
     collected data as it flowed between the data centres of large service firms
     such as Yahoo and  Google.  Your mail may have been  encrypted using SSL en
     route to the service's  front end, but it then flowed  in the clear between
     each company's data centres.

     [...] at  a meeting at  Princeton which Snowden attended  in the form  of a
     telepresence robot,  he pointed out  that a lot of  internet communications
     that appear to  be encrypted aren't really, as modern  websites use content
     delivery  networks (CDNs)  such as  Akamai  and Cloudflare;  while the  web
     traffic is encrypted from the user's laptop  or phone to the CDN's point of
     presente at their  ISP, it isn't encrypted on the  backhaul unless they pay
     extra  - which  most of  them don't.  So the  customer thinks  the link  is
     encrypted, and  it's protected from casual  snooping - but not  from nation
     states or from firms who can read backbone traffic.

**** Special collection
     The NSA and CIA jointly operate  the Special Collection Service (SCS) whose
     most visible activity  may be the plastic  panels near the roofs  of US and
     allied embassies worldwide;  these hide antennas for  hoovering up cellular
     communication (a program  known as ‘Stateroom’). Beyond  this, SCS implants
     collection equipment  in foreign telcos, Internet  exchanges and government
     facilities.  This can  involve classical spy tradecraft,  from placing bugs
     that monitor speech or  electronic communications, through recruiting moles
     in target  organisations, to  the covert deployment  of antennas  in target
     countries to tap internal microwave links.

     Close-access  operations  include  Tempest monitoring:  the  collection  of
     infor-  mation  leaked  by  the  electromagnetic  emissions  from  computer
     monitors  and  other equipment,  described  in  19.3.2. The  Snowden  leaks
     disclose the collection  of computer screen data  and other electromagnetic
     emanations  from  a  num-  ber  of countries’  embassies  and  UN  missions
     including those of India, Japan, Slovakia and the EU.

**** Bullrun and Edgehill
     Special  collection  increasingly   involves  supply-chain  tampering.  SCS
     routinely intercepts equipment such as routers being exported from the USA,
     adds surveillance  implants, repackages them  with factory seals  and sends
     them onward to customers.

     Bullrun  is the  NSA  codename,  and Edgehill  the  GCHQ  one, for  'crypto
     enabling', a $100m-a-year program of  tampering with supplies and suppliers
     at all levels of  the stack. [...]  Most of the  actual damage, though, was
     done  by   restrictions  on  cryptographic  key   length,  dovetailed  with
     diplomatic pressure  on allies  to enforce export  controls, so  that firms
     needing  export  licenses   could  have  their  arms  twisted   to  use  an
     'appropriate' standard, and was entangled  with the Crypto Wars. The result
     was  that many  of the  systems in  use today  were compelled  to use  weak
     cryptography, leading to  vulnerabilities in everything from  hotel and car
     door locks  to VPNs.  In addition to  that, supply-chain  attacks introduce
     covert vulnerabilities  into widely-used software; many  nation states play
     this game, along with some private actors.

**** Xkeyscore
     With such a vast collection of data,  you need good tools to search it. The
     Five Eyes search computer data using Xkeyscore, a distributed database that
     enables  an analyst  to search  collected  data remotely  and assemble  the
     results.  Exposed  on July  31  2013,  NSA  documents  describe it  as  its
     "widest-reaching" system for developing intelligence; it enables an analyst
     to  search  emails,  SMSes,  chats,   address  book  entries  and  browsing
     histories.

**** Longhaul
     Bulk key theft  and supply-chain tampering are not the  only ways to defeat
     cryptography. The  Xkeyscore training deck  gives an example: "Show  me all
     the VPN startups  in country X, and give  me the data so I  can decrypt and
     discover  the users".  VPNs  appear  to be  easily  defeated; a  decryption
     service  called  Longhaul ingests  ciphertext  and  returns plaintext.  The
     detailed  description of  cryptoanalytic techniques  is held  as /Extermely
     Compartmented Information/  (ECI) and is  not found in the  Snowden papers,
     but some of them talk of recent breakthroughs in cryptanalysis.

**** Quantum
     There is  a long  history of  attacks on protocols,  which can  be spoofed,
     replayed and manipulated in various ways. The best-documented NSA attack on
     Internet  traffic goes  under  the  codename of  Quantum  and involves  the
     dynamic exploitation of  one of the communication end-points.  Thus, to tap
     an  encrypted SSL/TLS  session to  a webmail  provider, the  Quantum system
     fires a ‘shot’  that exploits the browser.  There are  various flavours; in
     ‘Quantuminsert’, an  injected packet redirects  the browser to  a ‘Foxacid’
     attack server. Other  variants attack software updates  and the advertising
     networks whose code runs in mobile phone apps.

**** CNE (Computer and Network Exploitation)
     Is the generic NSA term for hacking, and  it can be used for more than just
     key theft  or TLS session  hijacking; it can be  used to acquire  access to
     traffic too.

*** China
    China is  now the leading  competitor to the USA,  being second not  just in
    terms of GDP (gross domestic product,  similar to /PIB/) but as a technology
    powerhouse. The  Chinese lack the NSA's  network of alliances and  access to
    global infrastructure (although they're working  hard at that). Within China
    itself, however,  they demand  unrestricted access to  local data.  [...] In
    2008, it  emerged that  the version  of Skype available  in Chinas  had been
    modified so that  messages were scanned for sensitive keywords  and, if they
    were found, the user's texts were uploaded to a server in China.

    [...]

    By 2020 the attacks had become more sophisticated, with a series of advanced
    persistent threats (APTs)  tracked by threat intelligence  firms. A campaign
    to hack  the phones of Uighurs  involved multiple zero-day attacks,  even on
    iPhones, that were delivered via  compromised Uighur websites; this targeted
    not  only  Uighurs in  China  but  the  diaspora  too. China  also  conducts
    industrial and commercial espionage, and Western agencies claim they exploit
    managed service  providers. Another  approach was attacking  software supply
    chains; a Chinese group variously  called Wicked Panda or Barium compromised
    software updates  from computer maker Asus,  a PC cleanup tool  and a Korean
    remote management tool, as well as three popular computer games, getting its
    malware installed  on millions  of machines;  rather than  launching banking
    trojans or ransomware, it was then used for spying.

    [...]

    Since 2018 there has been a  political row over whether Chinese firms should
    be permitted to sell routers and 5G  network hardware in NATO (same as OTAN)
    countries,   with   the   Trump  administration   blacklisting   Huawei   in
    May 2019. There had been a previous  spat over another Chinese firm, ZTE; in
    2018 GCHQ (Government Communications Headquarters) warned that ZTE equipment
    "would present  risk to  UK national  security that  could not  be mitigated
    effectively  or  practicably".  President  Trump  banned  ZTE  for  breaking
    sanctions on  North Korea and Iran,  but relented and allowed  its equipment
    back in the USA subject to security controls.

    [...]

    The UK banned the purchase of their telecomms equipment from the end of 2020
    and said it  would remove it from  UK networks by 2027.  Meanwhile, China is
    helping many  less developed  countries modernise  their networks,  and this
    access may help them rival the Five Eyes' scope in due course. Trade policy,
    industrial policy and cyber-defense strategy have become interwined in a new
    Cold War.

    Strategically, the question  may not be just whether China  could use Huawei
    routers to wiretap  other countries at scale, so much  as whether they could
    use  it in  time of  tension to  launch DDoS  attacks that  would break  the
    Internet by subverting BGP routing.

*** Russia
    Russia, like China, lacks America's  platform advantage and compensates with
    hacking teams  that use spear-phishing  and malware. Unlike China,  it takes
    the  low  road, acting  frequently  as  a  spoiler,  trying to  disrupt  the
    international order,  and sometimes  benefiting directly via  a rise  in the
    price of oil, its main export.

    [...]  Russia  took  down  30 electricity  substations  on  three  different
    distribution  systems within  half an  hour  of each  other, leaving  230000
    people  without  electricity  for  several  hours.  They  involved  multiple
    different attack  vectors that had been  implanted over a period  of months,
    and since they followed a Ukrainian attack on power distribution in Crimea -
    and  switched equipment  off when  they could  have destroyed  it instead  -
    seemed  to have  been intended  as  a warning.  This attack  was still  tiny
    compared with the other effects of the conflict, which included the shooting
    down of a Malaysian Airlines airliner with  the loss of all on board; but it
    was the first cyber-attack to disrupt  mains electricity. Finally on June 27
    2017 came  the NotPetya attack  - by far  the most damaging  cyber-attack to
    date.

    The NotPetya  worm was  initially distributed using  the update  service for
    MeDoc,  the accounting  software used  by  the great  majority of  Ukrainian
    businesses.  It  then  spread  laterally  in  organisations  across  Windows
    file-shares  using the  EternalBlue vulnerability,  an NSA  exploit with  an
    interesting  history.  From  March 2016,  a  Chinese gang  started using  it
    against targets  in Vietnam,  Hong Kong  and the  Philippines, perhaps  as a
    result  of finding  and reverse  engineering it  (it’s said  that you  don’t
    launch a  cyberweapon; you share  it).  It was leaked  by a gang  called the
    ‘Shadow  Brokers’ in  April 2017,  along with  other NSA  software that  the
    Chinese didn’t deploy,  and then used by the Russians  in June. The NotPetya
    worm  used  EternalBlue  together  with  the  Mimikatz  tool  that  recovers
    passwords  from  Windows   memory.  The  worm’s  payload   pretended  to  be
    ransomware; it  encrypted the infected  computer’s hard disk and  demanded a
    ransom of $300 in  bitcoin. But there was no mechanism  to decrypt the files
    of  computer owners  who paid  the ransom,  so it  was really  a destructive
    service-denial worm.  The only  way to  deal with it  was to  re-install the
    operating system and restore files from backup.

*** Crooks
    Cybercrime is now about  half of all crime, both by volume  and by value, at
    least in developed countries.

**** Malware devs
     In addition to the several hundred software engineers who write malware for
     the  world's intelligence  agencies  and their  contractors,  there may  be
     hundreds of people  writing malware for the criminal  market; nobody really
     knows (though we can monitor traffic on hacker forums to guess the order of
     magnitude).

     Within this  community there are  specialists. Some concentrate  on turning
     vulnerabilities  into  exploits, a  nontrivial  task  for modern  operating
     systems  that  use  stack  canaries,   ASLR  and  other  techniques.  Other
     specialise in  the remote access  Trojans that the exploits  install; other
     build the  peer-to-peer and DGA software  for resilient command-and-control
     communications; yet others design specialised  payloads for bank fraud. The
     highest-value  operations seem  to  be platforms  that  are maintaned  with
     constant  upgrades  to  cope  with  the  latest  countermeasures  from  the
     anti-virus  companies.  Within each  specialist  market  segment there  are
     typically a  handful of operators,  so that when we  arrest one of  them it
     makes a difference for a while.

**** Ransomware
     A number of professional gangs  penetrate systems, install ransomware, wait
     until several days  or weeks of backup data have  been encrypted and demand
     substantial sums of bitcoin.
