:PROPERTIES:
:ID:       7972dc99-50c7-4c2e-946c-df7fa41c3154
:END:
#+title: [Security] Economics
* Source

Author: Ross Anderson
Title: [Security Engineering] Economics
Year: 2021

* Summary

Here I'll save my notes related to the 8th chapter of the book Security
Engineering.
  
#+BEGIN_COMMENT
  The great fortunes of the information age lie in the hands of companies that
  have established proprietary architectures that are used by a large installed
  base of locked-in customers.
#+END_COMMENT

In general, people won't change their behaviour unless they have an incentive
to.

In this chapter I first describe how we analyse monopolies in the classical
economic model, how information goods and services markets are different, and
how network effects and technical lock-in make monopoly more likely. I then look
at asymmetric information, another source of market power. Next is game theory,
which enables us to analyse whether people will cooperate or compete; and
auction theory, which lets us understand the working of the ad markets that
drive much of the Internet - and how they fail. These basics then let us analyse
key components of the information security ecosystem, such as the software
patching cycle. We also get to understand why systems are less reliable than
they should be: why there are too many vulnerabilities and why too few
cyber-crooks get caught.

** Classical economics

Modern economics is an enormous field covering many different aspects of human
behaviour. The parts of it that have found application in security so far are
largely drawn from:

+ Microeconomics;
+ Game theory;
+ Behavioral economics.

** Economics of cybercrime

[...] psychologically normal people don’t like harming others; people who do so
tend to have low empathy, perhaps because of childhood abuse, or (more often) to
have minimisation strategies to justify their actions. Bank robbers see bankers
as the real exploiters; soldiers dehumanise the enemy as ‘gooks’ or ‘terrs’; and
most common murderers see their crimes as a matter of honour. “She cheated on
me” and “He disrespected me” are typical triggers; we discussed the mechanisms
in section 3.2.4. These mechanisms go across to the world of online and
electronic fraud. Hackers on the wrong side of the law tend to feel their
actions are justified anyway: hacktivists are political activists after all,
while cyber-crooks use a variety of minimisation strategies to avoid feeling
guilty. Some Russian cybercrooks take the view that the USA screwed Russia over
after 1989, so they’re just getting their own back (and they’re sup- ported in
this by their own government’s attitudes and policies). As for bankers who dump
fraud risks on customers, they talk internally about ‘the avalanche of
fraudulent risks of fraud’ they’d face if they owned up to security holes.
