:PROPERTIES:
:ID:       ac1af467-8d9d-436b-ba1c-2c57251aa93b
:END:
#+title: [Azure] AI-900
#+date: [2022-02-14 seg 18:25]

Microsoft Azure Virtual Training Day: AI Fundamentals

On 02-14-2022 I have participated in a session of the Microsoft Azure Virtual
Training Day focused in the AI Fundamentals services.

Instructor: Tycho Juta
His LinkedIn: https://linkedin.com/in/tychojuta

Principles of responsible AI:
- Fairness
- Reliability & safety
- Privacy & security
- Inclusiveness
- Transparency
- Accountability

https://aka.ms/learn-artificial-intelligence

*** Azure Machine Learning

"Creating predictive models by finding relationships in data."
    
- Regression
- Classification
- Clusterization

*** Some useful links shared in presentation

  Responsible AI - https://www.microsoft.com/ai/responsible-ai

  Cards Demo - https://aka.ms/hci-demo

  Learn more - https://aka.ms/learn-artificial-intelligence

  Machine Learning Demo - https://aka.ms/No-code-automl

  Computer Vision Demo - https://aidemos.microsoft.com/computer-vision

  Image Classification Demo -
  https://aka.ms/learn-image-classification

  Learn more - https://aka.ms/explore-computer-vision

  Natural Language Processing Demo -
  https://aidemos.microsoft.com/text-analytics

  Text Analytics Demo - https://aidemos.microsoft.com/luis/demo

  Language Understanding Demo - https://aka.ms/learn-luis

  Using a Bot Demo -
  https://www.microsoft.com/en-us/research/project/health-bot/

  Learn more - https://aka.ms/explore-bots

  QnA Maker Link - https://www.qnamaker.ai/

  Learn more - https://aka.ms/explore-nlp

  You can find demos here - https://aidemos.microsoft.com/

*** Voucher information
  
- How do I get my exam voucher?

You will receive an email with instructions after the event concludes on how to
access your exam discount for a single attempt of AI-900 (https://aka.ms/ai900)
that will be linked automatically with your Microsoft Certification Dashboard
(https://docs.microsoft.com/en-us/learn/certifications/) in 5 business days. The
exam discount is valid for 90 days. See FAQ for further info
-https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWG1g3.

- Any tip on how to succeed in AI-900 exam?

Go through the information at https://aka.ms/aifunpath.


** What is AI?

Simply put, AI is the creation of software that imitates human behaviors and
capabilities. Key elements include:

- Machine learning;
- Anomaly detection;
- Computer vision;
- Natural language processing;
- Conversational AI.

** Azure machine learning

What? Is a cloud service that you can use to train and manage machine learning
models.

How? Math and statistics. Classification (predicting categories or
classes). Regression (predicting numeric values). Time series forecasting
(predicting numeric values at a future point in time).

The automated machine learning capability in Azure Machine Learning supports
supervised machine learning models - in other words, models for which the
training data includes known label values.

*** Compute targets overview

+ Compute Instances:

  Development workstations that data scientists can use to work with data and
  models.

+ Compute Clusters:

  Scalable clusters of virtual machines for on-demand processing of experiment
  code.

+ Inference Clusters:

  Deployment targets for predictive services that use your trained models.

+ Attached Compute:

  Links to existing Azure compute resources, such as Virtual Machines or Azure
  Databricks clusters.

* Azure computer vision

- Custom vision:
  
  A dedicated resource for the custom vision service, which can be training, a
  prediction, or both resources.
  
- Cognitive services:
  
  A general cognitive services resource that includes Custom Vision along with
  many other cognitive services. You can use this type of resource for training,
  prediction, or both.

** Uses of image classification

- Product identification:

  Performing visual searches for specific products in online searches or even,
  in-store using a mobile device.

- Disaster investigation:

  Identifying key infrastructure for major disaster preparation efforts. For
  example, identifying bridges and roads in aerial images can help disaster
  relief teams plan ahead in regions that are not well mapped.

- Medical diagnosis:

  Evaluating images from X-ray or MRI devices could quickly classify specific
  issues found as cancerous tumors, or many other medical conditions related to
  medical imaging diagnosis.

Most modern image classification solutions are based on deep learning techniques
that make use of convolutional neural networks (CNNs) to uncover patterns in the
pixels that correspond to particular classes. Training an effective CNN is a
complex task that requires considerable expertise in data science and machine
learning.
