:PROPERTIES:
:ID:       ac1af467-8d9d-436b-ba1c-2c57251aa93b
:END:
#+title: [Azure] AI-900
#+date: [2022-02-14 seg 18:25]

* Virtual Training Day: AI Fundamentals

On 02-14-2022 I have participated in a session of the Microsoft Azure Virtual
Training Day focused in the AI Fundamentals services.

Instructor: Tycho Juta
His LinkedIn: https://linkedin.com/in/tychojuta

Principles of responsible AI:
- Fairness
- Reliability & safety
- Privacy & security
- Inclusiveness
- Transparency
- Accountability

https://aka.ms/learn-artificial-intelligence

*** Azure Machine Learning

"Creating predictive models by finding relationships in data."
    
- Regression
- Classification
- Clusterization

*** Some useful links shared in presentation

  Responsible AI - https://www.microsoft.com/ai/responsible-ai

  Cards Demo - https://aka.ms/hci-demo

  Learn more - https://aka.ms/learn-artificial-intelligence

  Machine Learning Demo - https://aka.ms/No-code-automl

  Computer Vision Demo - https://aidemos.microsoft.com/computer-vision

  Image Classification Demo -
  https://aka.ms/learn-image-classification

  Learn more - https://aka.ms/explore-computer-vision

  Natural Language Processing Demo -
  https://aidemos.microsoft.com/text-analytics

  Text Analytics Demo - https://aidemos.microsoft.com/luis/demo

  Language Understanding Demo - https://aka.ms/learn-luis

  Using a Bot Demo -
  https://www.microsoft.com/en-us/research/project/health-bot/

  Learn more - https://aka.ms/explore-bots

  QnA Maker Link - https://www.qnamaker.ai/

  Learn more - https://aka.ms/explore-nlp

  You can find demos here - https://aidemos.microsoft.com/

*** Voucher information
  
- How do I get my exam voucher?

You will receive an email with instructions after the event concludes on how to
access your exam discount for a single attempt of AI-900 (https://aka.ms/ai900)
that will be linked automatically with your Microsoft Certification Dashboard
(https://docs.microsoft.com/en-us/learn/certifications/) in 5 business days. The
exam discount is valid for 90 days. See FAQ for further info
-https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWG1g3.

- Any tip on how to succeed in AI-900 exam?

Go through the information at https://aka.ms/aifunpath.


** What is AI?

Simply put, AI is the creation of software that imitates human behaviors and
capabilities. Key elements include:

- Machine learning;
- Anomaly detection;
- Computer vision;
- Natural language processing;
- Conversational AI.

** Azure machine learning

What? Is a cloud service that you can use to train and manage machine learning
models.

How? Math and statistics. Classification (predicting categories or
classes). Regression (predicting numeric values). Time series forecasting
(predicting numeric values at a future point in time).

The automated machine learning capability in Azure Machine Learning supports
supervised machine learning models - in other words, models for which the
training data includes known label values.

*** Compute targets overview

+ Compute Instances:

  Development workstations that data scientists can use to work with data and
  models.

+ Compute Clusters:

  Scalable clusters of virtual machines for on-demand processing of experiment
  code.

+ Inference Clusters:

  Deployment targets for predictive services that use your trained models.

+ Attached Compute:

  Links to existing Azure compute resources, such as Virtual Machines or Azure
  Databricks clusters.

* Azure computer vision

- Custom vision:
  
  A dedicated resource for the custom vision service, which can be training, a
  prediction, or both resources.
  
- Cognitive services:
  
  A general cognitive services resource that includes Custom Vision along with
  many other cognitive services. You can use this type of resource for training,
  prediction, or both.

** Uses of image classification

- Product identification:

  Performing visual searches for specific products in online searches or even,
  in-store using a mobile device.

- Disaster investigation:

  Identifying key infrastructure for major disaster preparation efforts. For
  example, identifying bridges and roads in aerial images can help disaster
  relief teams plan ahead in regions that are not well mapped.

- Medical diagnosis:

  Evaluating images from X-ray or MRI devices could quickly classify specific
  issues found as cancerous tumors, or many other medical conditions related to
  medical imaging diagnosis.

Most modern image classification solutions are based on deep learning techniques
that make use of convolutional neural networks (CNNs) to uncover patterns in the
pixels that correspond to particular classes. Training an effective CNN is a
complex task that requires considerable expertise in data science and machine
learning.

** Object detection

   Is a form of machine learning based computer vision in which a model is
   trained to recognize individual types of objects in an image, and to identify
   their location in the image.

*** Usage example

    - Checking for building safety:

      Evaluating the safety of a building by analyzing footage of its interior
      for the fire extinguishers or other emergency equipment.

    - Driving assistance:

      Creating software for self-driving cars or vehicles with lane assist
      capabilities. The software can detect whether there is a car in another
      lane, and whether the driver's car is within its own lanes.

    - Detecting tumors:

      Medical imaging such as an MRI or x-rays that can detect known objects for
      medical diagnosis.

** Face service

   Face detection, analysis, and recognition is an important capability for
   artificial intelligence solutions. The Face cognitive service in Azure makes
   it easy integrate these capabilities into your applications.

*** Facial detection
   
    Face detection involves identifying regions of an image that contain a human
    face, typically by returning a bounding box coordinates that form a
    rectangle around the face.

*** Facial analysis

    Detect facial landmarks (nose, eyes, eyebrows, lips, etc), to train a
    machine learning model from which you can infer information about a person,
    such as their perceived emotional state.

*** Facial recognition

    Identify known individuals from their facial features.

*** Microsoft Azure services

    + Computer vision:
      Offers face detection and some basic face analysis, such as determining
      age.

    + Video indexer:
      Detect and identify faces in a video.

    + Face:
      Offers pre-built algorithms that can detect, recognize and analyze faces.

** Optical character recognition (OCR)

   Optical character recognition (OCR) enables artificial intelligence (AI)
   systems to read text in images, enabling applications to extract information
   from photographs, scanned documents, and other sources of digitized text.

   This is related to:

   + Process written or printed text

   The basic foundation of processing printed text is optical character
   recognition (OCR), in which a model can be trained to recognize individual
   shapes as letters, numerals, punctuation, or other elements of text. Much of
   the early work on implementing this kind of capability was performed by
   postal services to support automatic sorting of mail based on postal
   codes. Since then, the state-of-the-art for reading text has moved on, and
   it's now possible to build models that can detect printed or handwritten text
   in an image and read it line-by-line or even word-by-word.

   At the other end of the scale, there is machine reading comprehension (MRC),
   in which AI systems not only reads the text characters, but can use a
   semantic model to interpret what the text is about.

*** Uses of OCR

    + note taking;
    + digitizing forms, such as medical records or historical documents;
    + scanning printed or handwritten checks for bank deposits.

*** Azure resources for computer vision

    + Computer Vision:

      A specific resource for the Computer Vision service. Use this resource
      type if you don't intend to use any other cognitive services, or if you
      want to track utilization and costs for your Computer Vision resource
      separately.

    + Cognitive Services:

      A general cognitive services resource that includes Computer Vision along
      with many other cognitive services; such as Text Analytics, Translator
      Text, and others. Use this resource if you plan to use multiple cognitive
      services and want to simplify administration and development.

*** Knowledge check

    1. You want to extract text from images and then use the Text Analytics
       service to analyze the text. You want developers to require only one key
       and endpoint to access all of your services. What kind of resource
       should you create in your Azure subscription?

       A: Cognitive Services. This resource support both Computer Vision for text
       extraction, and Text Analytics for text analysis.

    2. You plan to use the Computer Vision service to read text in a large PDF
       document. Which API should you use?

       A: The Read API. This API is better suited for larger images but it runs
       asynchronously so it will not block your application while it is running.
