:PROPERTIES:
:ID:       71994e19-648e-4350-b699-e23697788910
:END:
#+title: [Workshop] Serviços e ferramentas gratuitas na nuvem microsoft

Notas  referentes  ao  evento  online  chamado /Azure  na  faixa!!!  Serviços  e
ferramentas  gratuitas   na  nuvem   microsoft/  realizado  pelo   canal  Coding
Night. [[https://www.youtube.com/watch?v=tn0gf_mz0M0][Link para o vídeo]].

- Renato Groffe
- Walter (@waltercoan)
- Alexandre Malavasi (@alemalavasi)
- Robson Araujo (@RobsonROX)
- Diego Matos

Azure  tem uma  free tier  muito  generosa com  uma  série de  recursos que  são
gratuitos ou tem  pelo menos uma tier que é  sempre gratuita. Entretanto, alguns
serviços apesar  de serem gratuitos, utilizam  outros recursos que não  são, por
exemplo AKS que o serviço de kubernetes é gratuito mas temos custos relacionados
a máquina que executará o comando.

Bancos de dados gratuitos na Azure

CosmosDB -> limite de 400RU, precisa configurar o throughput.
Azure Storage -> tables.

+ É possível setar um valor limite de gastos através da UI.

** Serviços gratuitos

https://azure.microsoft.com/pt-br/free/free-account-faq/#free-services

Azure DevOps:
  - Excelente para CI/CD de aplicações.
  - Algumas empresas usam esse serviço para gerenciar pipelines em outras nuvens.

** Precificação

Fazer uma escala pequena do projeto para entender como os preços funcionam antes
de criar o ambiente de produção.  Atualmente temos alguns recursos que podem ser
utilizados para evitar este cenário e agilizar o processo de provisionamento.
   
+ Azure calculator.
  https://azure.microsoft.com/pt-br/pricing/calculator/
  
+ TCO (Total Cost Ownership) calculator.
  Bacana para saber se vale a pena manter a estrutura on-premise ou mover para a
  nuvem.
  https://azure.microsoft.com/pt-br/pricing/tco/calculator/ 

** Certificação

Certificações básicas são as da série 900.

- AZ-900
  Foco em conceitos do Azure.
- DP-900
  Foco em serviços de banco no Azure.
- SC-900
  Conceitos de serviços de segurança no Azure.
- AI-900
- MS-900

*Dica  valiosa: Dá  pra conseguir  vouchers  pras provas  através dos  Microsoft
 Training Day.*
https://www.microsoft.com/en-us/trainingdays

*** Dicas de estudos

+ Microsoft learning
+ Livros oficiais da Pearson
+ Whizlabs
+ No site oficial da certificação podemos ter acesso a provas de exemplo

** Artigos relevantes

+ [[https://medium.com/@robson_rocha/list/o-caminho-para-se-tornar-um-arquiteto-azure-atraves-das-certificacoes-microsoft-5e998ce7289b][O caminho para se tornar um Arquiteto Azure através das Certificações Microsoft]]
+ [[https://renatogroffe.medium.com/exame-az-900-azure-fundamentals-dicas-e-conte%C3%BAdos-gratuitos-5af72d1a8a29][Exame AZ-900 - Azure Fundamentals: dicas e conteúdos gratuitos]]
