:PROPERTIES:
:ID:       379d7da1-13cf-490a-8015-8de58be3fd59
:END:
#+title: [Article] GPG encryption
#+date: [2022-06-18 sáb 15:49]

#+begin_quote
  Cryptography is where security engineering meets mathematics.

  --- [1]
#+end_quote

* Introduction

There is a very big area in computer systems focused only to deal with
information security. Everyday, deliberately we share great details of ourselves
in the internet, as virtual data. This data, when collected by some bad actor
with wrong incentives can be used against you in many different ways, ultimately
enabling some group to manipulate you.

If you never thought about it, please consider it now.

With this in mind, some pretty smart people use their time to enhance the
security, where one of the most used tools in this regard is called GPG
encryption.

In this article my goal is to share some definitions related to the encryption
field, present how to use GPG encryption in a Linux system and finally conclude
with final thoughts.

With no further ado, let's start defining some terms.

** Crypt... what?

It's pretty common to use the word "crypto" to refer for different concepts,
usually for both the process of applying some encryption technique to some
information and the process of breaking it.

The following quote dismistifies the term presenting some accurate vocabulary
describe each of those activities.

#+begin_quote
  *Cryptography* refers to the science and art of designing ciphers;
  *cryptanalysis* to the science and art of breaking them; while *cryptology*,
  often shortened to just crypto, is the study of both. The input to an
  encryption process is commonly called the plaintext or cleartext, and the
  output the ciphertext.

  --- [1]
#+end_quote
   
** Hash

** Simmetric encryption

** Assimetric encryption

** Signature verification

* [Linux] How to start using it?

In this tutorial I'll present the commands to run considering that you're using
a system with the *apt* package manager (Ubuntu, for example).

To install and start using the GPG tool one can simply run those commands:

#+begin_src bash
  # install the GPG tool
  apt install gnupg

  # generate your keys
  gpg --gen-key
  # fulfill next questions...
  # select the algorithm used to generate your keys,
  # the size, your name, e-mail, ..., and finally your
  # passphrase (please, use something hard to guess).

  # by default your keys will be stored in
  # ~/.gnupg/
#+end_src

After creating your keys, make sure to keep the private key hidden, otherwise
all of this would be useless.

Then, add your key to some key server. In the sequence we explain how to do this
for the Ubuntu key server.

*** Key sharing

Although there are lots of options to share your public GPG key, one of the most
easy is the Ubuntu key server.

You can find it in [[https://keyserver.ubuntu.com/][this link]].

*** E-mail - Chrome extension

One of the most used scenario for the GPG encryption is to deal with e-mail
security. If you use Chrome or some variant of it, consider taking a look at
this extension called [[https://chrome.google.com/webstore/detail/flowcrypt-encrypt-gmail-w/bnjglocicdkmhmoohhfkfkbbkejdhdgc?hl=en-US][FlowCrypt]].

*** Cheatsheet

Everybody likes cheatsheets. This is a pretty useful tool to consult for
commands and quick tutorials on how to use something. For GPG there is this
cheatsheet which I use during my daily routine:

+ [[http://irtfweb.ifa.hawaii.edu/~lockhart/gpg/][GPG cheatsheet]].

Make sure to consult this link when you forget about some feature or command.

* Conclusion

* References

[1] - Security Engineering. Anderson, R. 3rd edition.
[2] - [[https://www.gnupg.org/][GnuPG official site]].
[3] - [[https://en.wikipedia.org/wiki/GNU_Privacy_Guard][GNU Privacy Guard. Wikipedia]].
[4] - [[https://latacora.micro.blog/2019/07/16/the-pgp-problem.html][The PGP Problem. Latacora]].
