:PROPERTIES:
:ID:       2ab6f31b-f3e5-4073-a72a-d767d244da96
:END:
#+title: Plantas: Suculentas
#+date: [2022-01-30 dom 11:29]

Baseado no conteúdo do vídeo [[https://www.youtube.com/watch?v=7Hyk_WMiaAk&ab_channel=Cultivando][Dicas de ouro para REGAR suas SUCULENTAS]].

Existe também o blog: http://www.cultivando.com.br/.

- Dica 1:

  Suculentas  que pegam  mais sol  precisam de  mais água  pois elas  secam mais
  rápido.

- Dica 2:

  Não regue demais a suculenta para evitar matar suas raízes afogadas.

- Dica 3:

  Se a terra  ainda estiver úmida/enxarcada então espere um  pouco mais antes de
  regar  novamente.  Suculentas são  plantas  que  demandam relativamente  pouca
  água. Você pode usar seu dedo para fazer essa verificação.

- Dica 4:

  Não acredite na regra de usar apenas  uma seringa para aguar a suculenta, essa
  quantidade  é geralmente  muito  pouca. O  que  acontece é  que  as raízes  da
  suculenta se desenvolvem onde tem água. É bom regar até começar a sair água do
  vaso.

- Dica 5:

  Independente de  ser dia ou noite  o importante é  manter o solo úmido  para a
  planta ter uma melhor qualidade.

- Dica 6:

  Não plante em  vasos sem furos. Em um  vaso desse tipo não é  possível ver até
  onde vai o nível da água. É importante não deixar a terra inundada.

- Dica 7:

  Não siga regras fixas, adapte para o seu cenário.

- Dica 8:

  Cada   tipo   de  suculenta   precisa   de   uma  quantidade   específica   de
  água. Suculentas com  folhas mais finas em geral secam  mais rápido que outras
  suculentas com folhas mais grossas. O  ideal, portanto, para as suculentas com
  folhas mais finas, é deixar a terra mais úmida.

  Para saber  se a suculenta  está com a quantidade  ideal de água  é necessário
  verificar o  estado das folhas  desta. Se a folha  ficar mais murcha,  mole ou
  enrrugada, significa que ela precisa de mais água.
